# Generated by Django 4.2.23 on 2025-07-24 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Android', 'Android'), ('iOS', 'iOS'), ('AMP', 'AMP'), ('PWA', 'PWA'), ('Desktop', 'Desktop')], default='Website', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('source', models.CharField(choices=[('Website', 'Website'), ('Android', 'Android'), ('iOS', 'iOS'), ('AMP', 'AMP'), ('PWA', 'PWA'), ('Desktop', 'Desktop')], default='Website', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('track', models.TextField(blank=True, editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Delete', 'Delete')], default='Active', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
